version: "3"
services:
  fuseki:
    hostname: fuseki
    container_name: fuseki
    build: .
    environment:
       - "ADMIN_PASSWORD=admin"
       - "QUERY_TIMEOUT=500000"
       - "JVM_ARGS=-Xmx32g"
       - "TDB=2"
       # "FUSEKI_DATASET_1=hpa"
    ports:
        - "3030:3030"
    volumes:
      # Overwrite FUSEKI_HOME/shiro.ini for use by entrypoint
      - "./shiro.ini:/jena-fuseki/shiro.ini"
      - "./data:/fuseki-base/databases"

  apacheds:
    hostname: apacheds
    container_name: apacheds
    image: openmicroscopy/apacheds
    ports:
        - "10389:10389"
    healthcheck:
        test: ["CMD", "curl", "ldap://localhost:10389"]
        interval: 30s
        timeout: 10s
        retries: 5

  setup:
    image: openmicroscopy/apacheds
    volumes: ["./setup.sh:/setup.sh"]
    entrypoint: "bash"
    command: "/setup.sh"
    restart: "no"
    environment:
       - "LDAP_HOST=apacheds"
       - "QUERY_TIMEOUT=500000"
    depends_on:
      - apacheds
