version: "3"
services:
  fuseki:
    hostname: fuseki
    build: .
    environment:
       - "ADMIN_PASSWORD=admin"
       - "QUERY_TIMEOUT=5000000"
       - "ENABLE_UPDATE=true"
       - "ENABLE_UPLOAD=true"
       - "JVM_ARGS=-Xmx8g"
       - "TDB=2"
       # "FUSEKI_DATASET_1=hpa"
    ports:
        - "4040:3030"
    volumes:
      # Overwrite FUSEKI_HOME/shiro.ini for use by entrypoint
      - "./shiro.ini:/jena-fuseki/shiro.ini"
      - "./data:/fuseki-base/databases"
      - "./web.xml:/jena-fuseki/webapp/WEB-INF/web.xml"
      - "./static/d3sparql:/jena-fuseki/webapp/static/d3sparql"

  apacheds:
    hostname: apacheds
    image: openmicroscopy/apacheds
    healthcheck:
        test: ["CMD", "curl", "ldap://localhost:10389"]
        interval: 30s
        timeout: 10s
        retries: 5

  setup:
    image: openmicroscopy/apacheds
    volumes: ["./setup.sh:/setup.sh"]
    entrypoint: "bash"
    command: "/setup.sh"
    restart: "no"
    environment:
       - "LDAP_HOST=apacheds"
    depends_on:
      - apacheds

  yasgui:
    image: erikap/yasgui
    environment:
     DEFAULT_SPARQL_ENDPOINT: "http://idr.semscape.org:3030/ds/sparql"
     ENABLE_ENDPOINT_SELECTOR: "true"
    ports:
        - "4000:8000"

  nginx:
    image: nginx
    ports:
        - "4080:80"
    volumes:
      - "./static/d3sparql:/app/static"
      - "./nginx.conf:/etc/nginx/nginx.conf"
