#!/bin/bash

set -e
set -x


# sudo docker run --rm -v $PWD:/src/:ro -v $PWD...data --entrypoint=bash $IMAGE src/load.sh

URI=http://idr.semscape.org:3030/
go(){
    $TDBLOADER --graph=$URI/hpa $FUSEKI_BASE/databases/hpa/$1
}

go hpa_omero_main.ttl.gz
go hpa_omero_xaa.ttl.gz
go hpa_omero_xab.ttl.gz
go hpa_omero_xac.ttl.gz
go hpa_omero_xad.ttl.gz
go hpa_omero_xae.ttl.gz
go hpa_omero_xaf.ttl.gz
go hpa_omero_xag.ttl.gz
go hpa_omero_xah.ttl.gz
go hpa_omero_xai.ttl.gz
go hpa_omero_xaj.ttl.gz
go hpa_omero_xak.ttl.gz
go hpa_omero_xal.ttl.gz
go hpa_omero_xam.ttl.gz
go hpa_omero_xan.ttl.gz
go hpa_omero_xao.ttl.gz
go hpa_omero_xap.ttl.gz
go hpa_omero_xaq.ttl.gz
go hpa_omero_xar.ttl.gz
go hpa_omero_xas.ttl.gz
go hpa_omero_xat.ttl.gz
go hpa_omero_xau.ttl.gz
go hpa_omero_xav.ttl.gz
go hpa_omero_xaw.ttl.gz
go hpa_omero_xax.ttl.gz
go hpa_omero_xay.ttl.gz
go hpa_omero_xaz.ttl.gz
go hpa_omero_xba.ttl.gz
go hpa_omero_xbb.ttl.gz
go hpa_omero_xbc.ttl.gz
go hpa_omero_xbd.ttl.gz
go hpa_omero_xbe.ttl.gz
go hpa_omero_xbf.ttl.gz
go hpa_omero_xbg.ttl.gz
go hpa_omero_xbh.ttl.gz
go hpa_omero_xbi.ttl.gz
go hpa_omero_xbj.ttl.gz
go hpa_omero_xbk.ttl.gz
go hpa_omero_xbl.ttl.gz
go hpa_omero_xbm.ttl.gz
go hpa_omero_xbn.ttl.gz
go hpa_omero_xbo.ttl.gz
go hpa_omero_xbp.ttl.gz
go hpa_omero_xbq.ttl.gz
go hpa_omero_xbr.ttl.gz
go hpa_omero_xbs.ttl.gz
go hpa_omero_xbt.ttl.gz
go hpa_omero_xbu.ttl.gz
go hpa_omero_xbv.ttl.gz
go hpa_omero_xbw.ttl.gz
go hpa_omero_xbx.ttl.gz
go hpa_omero_xby.ttl.gz
go hpa_omero_xbz.ttl.gz
go hpa_omero_xca.ttl.gz
go hpa_omero_xcb.ttl.gz
go hpa_omero_xcc.ttl.gz
go hpa_omero_xcd.ttl.gz
go hpa_omero_xce.ttl.gz
go hpa_omero_xcf.ttl.gz
go hpa_omero_xcg.ttl.gz
go hpa_omero_xch.ttl.gz
go hpa_omero_xci.ttl.gz
go hpa_omero_xcj.ttl.gz
go hpa_omero_xck.ttl.gz
go hpa_omero_xcl.ttl.gz
go hpa_omero_xcm.ttl.gz
go hpa_omero_xcn.ttl.gz
go hpa_omero_xco.ttl.gz
go hpa_omero_xcp.ttl.gz
go hpa_omero_xcq.ttl.gz
go hpa_omero_xcr.ttl.gz
go hpa_omero_xcs.ttl.gz
go hpa_omero_xct.ttl.gz
go hpa_omero_xcu.ttl.gz
go hpa_omero_xcv.ttl.gz
go hpa_omero_xcw.ttl.gz
go hpa_omero_xcx.ttl.gz
go hpa_omero_xcy.ttl.gz
go hpa_omero_xcz.ttl.gz
go hpa_omero_xda.ttl.gz
go hpa_omero_xdb.ttl.gz
go hpa_omero_xdc.ttl.gz
go hpa_omero_xdd.ttl.gz
go hpa_omero_xde.ttl.gz
go hpa_omero_xdf.ttl.gz
go hpa_omero_xdg.ttl.gz
go hpa_omero_xdh.ttl.gz
go hpa_omero_xdi.ttl.gz
go hpa_omero_xdj.ttl.gz
go hpa_omero_xdk.ttl.gz
go hpa_omero_xdl.ttl.gz
go hpa_omero_xdm.ttl.gz
go hpa_omero_xdn.ttl.gz
go hpa_omero_xdo.ttl.gz
go hpa_omero_xdp.ttl.gz
go hpa_omero_xdq.ttl.gz
go hpa_omero_xdr.ttl.gz
go hpa_omero_xds.ttl.gz
go hpa_omero_xdt.ttl.gz
go hpa_omero_xdu.ttl.gz
go hpa_omero_xdv.ttl.gz
go hpa_omero_xdw.ttl.gz
go hpa_omero_xdx.ttl.gz
go hpa_omero_xdy.ttl.gz
go hpa_omero_xdz.ttl.gz
go hpa_omero_xea.ttl.gz
go hpa_omero_xeb.ttl.gz
go hpa_omero_xec.ttl.gz
go hpa_omero_xed.ttl.gz
go hpa_omero_xee.ttl.gz
go hpa_omero_xef.ttl.gz
go hpa_omero_xeg.ttl.gz
go hpa_omero_xeh.ttl.gz
go hpa_omero_xei.ttl.gz
go hpa_omero_xej.ttl.gz
go hpa_omero_xek.ttl.gz
go hpa_omero_xel.ttl.gz
go hpa_omero_xem.ttl.gz
go hpa_omero_xen.ttl.gz
go hpa_omero_xeo.ttl.gz
go hpa_omero_xep.ttl.gz
go hpa_omero_xeq.ttl.gz
go hpa_omero_xer.ttl.gz
go hpa_omero_xes.ttl.gz
go hpa_omero_xet.ttl.gz
go hpa_omero_xeu.ttl.gz
go hpa_omero_xev.ttl.gz
go hpa_omero_xew.ttl.gz
go hpa_omero_xex.ttl.gz
go hpa_omero_xey.ttl.gz
go hpa_omero_xez.ttl.gz
go hpa_omero_xfa.ttl.gz
go hpa_omero_xfb.ttl.gz
go hpa_omero_xfc.ttl.gz
go hpa_omero_xfd.ttl.gz
go hpa_omero_xfe.ttl.gz
go hpa_omero_xff.ttl.gz
go hpa_omero_xfg.ttl.gz
go hpa_omero_xfh.ttl.gz
go hpa_omero_xfi.ttl.gz
go hpa_omero_xfj.ttl.gz
go hpa_omero_xfk.ttl.gz
go hpa_omero_xfl.ttl.gz
go hpa_omero_xfm.ttl.gz
go hpa_omero_xfn.ttl.gz
go hpa_omero_xfo.ttl.gz
go hpa_omero_xfp.ttl.gz
go hpa_omero_xfq.ttl.gz
go hpa_omero_xfr.ttl.gz
go hpa_omero_xfs.ttl.gz
go hpa_omero_xft.ttl.gz
go hpa_omero_xfu.ttl.gz
go hpa_omero_xfv.ttl.gz
go hpa_omero_xfw.ttl.gz
go hpa_omero_xfx.ttl.gz
go hpa_omero_xfy.ttl.gz
go hpa_omero_xfz.ttl.gz
go hpa_omero_xga.ttl.gz
go hpa_omero_xgb.ttl.gz
go hpa_omero_xgc.ttl.gz
go hpa_omero_xgd.ttl.gz
go hpa_omero_xge.ttl.gz
go hpa_omero_xgf.ttl.gz
go hpa_omero_xgg.ttl.gz
go hpa_omero_xgh.ttl.gz
go hpa_omero_xgi.ttl.gz
go hpa_omero_xgj.ttl.gz
go hpa_omero_xgk.ttl.gz
go hpa_omero_xgl.ttl.gz
go hpa_omero_xgm.ttl.gz
go hpa_omero_xgn.ttl.gz
go hpa_omero_xgo.ttl.gz
go hpa_omero_xgp.ttl.gz
go hpa_omero_xgq.ttl.gz
go hpa_omero_xgr.ttl.gz
go hpa_omero_xgs.ttl.gz
go hpa_omero_xgt.ttl.gz
go hpa_omero_xgu.ttl.gz
go hpa_omero_xgv.ttl.gz
go hpa_omero_xgw.ttl.gz
go hpa_omero_xgx.ttl.gz
go hpa_omero_xgy.ttl.gz
go hpa_omero_xgz.ttl.gz
go hpa_omero_xha.ttl.gz
go hpa_omero_xhb.ttl.gz
go hpa_omero_xhc.ttl.gz
go hpa_omero_xhd.ttl.gz
go hpa_omero_xhe.ttl.gz
go hpa_omero_xhf.ttl.gz
go hpa_omero_xhg.ttl.gz
go hpa_omero_xhh.ttl.gz
go hpa_omero_xhi.ttl.gz
go hpa_omero_xhj.ttl.gz
go hpa_omero_xhk.ttl.gz
go hpa_omero_xhl.ttl.gz
go hpa_omero_xhm.ttl.gz
go hpa_omero_xhn.ttl.gz
go hpa_omero_xho.ttl.gz
go hpa_omero_xhp.ttl.gz
go hpa_omero_xhq.ttl.gz
go hpa_omero_xhr.ttl.gz
go hpa_omero_xhs.ttl.gz
go hpa_omero_xht.ttl.gz
go hpa_omero_xhu.ttl.gz
go hpa_omero_xhv.ttl.gz
go hpa_omero_xhw.ttl.gz
go hpa_omero_xhx.ttl.gz
go hpa_omero_xhy.ttl.gz
go hpa_omero_xhz.ttl.gz
go hpa_omero_xia.ttl.gz
go hpa_omero_xib.ttl.gz
go hpa_omero_xic.ttl.gz
go hpa_omero_xid.ttl.gz
go hpa_omero_xie.ttl.gz
go hpa_omero_xif.ttl.gz
go hpa_omero_xig.ttl.gz
go hpa_omero_xih.ttl.gz
go hpa_omero_xii.ttl.gz
go hpa_omero_xij.ttl.gz
go hpa_omero_xik.ttl.gz
go hpa_omero_xil.ttl.gz
go hpa_omero_xim.ttl.gz
go hpa_omero_xin.ttl.gz
go hpa_omero_xio.ttl.gz
go hpa_omero_xip.ttl.gz
go hpa_omero_xiq.ttl.gz
go hpa_omero_xir.ttl.gz
go hpa_omero_xis.ttl.gz
go hpa_omero_xit.ttl.gz
go hpa_omero_xiu.ttl.gz
go hpa_omero_xiv.ttl.gz
go hpa_omero_xiw.ttl.gz
go hpa_omero_xix.ttl.gz
go hpa_omero_xiy.ttl.gz
go hpa_omero_xiz.ttl.gz
go hpa_omero_xja.ttl.gz
go hpa_omero_xjb.ttl.gz
go hpa_omero_xjc.ttl.gz
go hpa_omero_xjd.ttl.gz
go hpa_omero_xje.ttl.gz
go hpa_omero_xjf.ttl.gz
go hpa_omero_xjg.ttl.gz
go hpa_omero_xjh.ttl.gz
go hpa_omero_xji.ttl.gz
go hpa_omero_xjj.ttl.gz
go hpa_omero_xjk.ttl.gz
go hpa_omero_xjl.ttl.gz
go hpa_omero_xjm.ttl.gz
go hpa_omero_xjn.ttl.gz
go hpa_omero_xjo.ttl.gz
go hpa_omero_xjp.ttl.gz
go hpa_omero_xjq.ttl.gz
go hpa_omero_xjr.ttl.gz
go hpa_omero_xjs.ttl.gz
go hpa_omero_xjt.ttl.gz
go hpa_omero_xju.ttl.gz
go hpa_omero_xjv.ttl.gz
go hpa_omero_xjw.ttl.gz
go hpa_omero_xjx.ttl.gz
go hpa_omero_xjy.ttl.gz
go hpa_omero_xjz.ttl.gz
go hpa_omero_xka.ttl.gz
go hpa_omero_xkb.ttl.gz
go hpa_omero_xkc.ttl.gz
go hpa_omero_xkd.ttl.gz
go hpa_omero_xke.ttl.gz
go hpa_omero_xkf.ttl.gz
go hpa_omero_xkg.ttl.gz
go hpa_omero_xkh.ttl.gz
go hpa_omero_xki.ttl.gz
go hpa_omero_xkj.ttl.gz
go hpa_omero_xkk.ttl.gz
go hpa_omero_xkl.ttl.gz
go hpa_omero_xkm.ttl.gz
go hpa_omero_xkn.ttl.gz
go hpa_omero_xko.ttl.gz
go hpa_omero_xkp.ttl.gz
go hpa_omero_xkq.ttl.gz
go hpa_omero_xkr.ttl.gz
go hpa_omero_xks.ttl.gz
go hpa_omero_xkt.ttl.gz
go hpa_omero_xku.ttl.gz
go hpa_omero_xkv.ttl.gz
go hpa_omero_xkw.ttl.gz
go hpa_omero_xkx.ttl.gz
go hpa_omero_xky.ttl.gz
go hpa_omero_xkz.ttl.gz
go hpa_omero_xla.ttl.gz
go hpa_omero_xlb.ttl.gz
go hpa_omero_xlc.ttl.gz
go hpa_omero_xld.ttl.gz
go hpa_omero_xle.ttl.gz
go hpa_omero_xlf.ttl.gz
go hpa_omero_xlg.ttl.gz
go hpa_omero_xlh.ttl.gz
go hpa_omero_xli.ttl.gz
go hpa_omero_xlj.ttl.gz
go hpa_omero_xlk.ttl.gz
go hpa_omero_xll.ttl.gz
go hpa_omero_xlm.ttl.gz
go hpa_omero_xln.ttl.gz
go hpa_omero_xlo.ttl.gz
go hpa_omero_xlp.ttl.gz
go hpa_omero_xlq.ttl.gz
go hpa_omero_xlr.ttl.gz
go hpa_omero_xls.ttl.gz
go hpa_omero_xlt.ttl.gz
go hpa_omero_xlu.ttl.gz
go hpa_omero_xlv.ttl.gz
go hpa_omero_xlw.ttl.gz
go hpa_omero_xlx.ttl.gz
go hpa_omero_xly.ttl.gz
go hpa_omero_xlz.ttl.gz
go hpa_omero_xma.ttl.gz
go hpa_omero_xmb.ttl.gz
go hpa_omero_xmc.ttl.gz
go hpa_omero_xmd.ttl.gz
go hpa_omero_xme.ttl.gz
go hpa_omero_xmf.ttl.gz
go hpa_omero_xmg.ttl.gz
go hpa_omero_xmh.ttl.gz
go hpa_omero_xmi.ttl.gz
go hpa_omero_xmj.ttl.gz
go hpa_omero_xmk.ttl.gz
go hpa_omero_xml.ttl.gz
go hpa_omero_xmm.ttl.gz
go hpa_omero_xmn.ttl.gz
go hpa_omero_xmo.ttl.gz
go hpa_omero_xmp.ttl.gz
go hpa_omero_xmq.ttl.gz
go hpa_omero_xmr.ttl.gz
go hpa_omero_xms.ttl.gz
go hpa_omero_xmt.ttl.gz
go hpa_omero_xmu.ttl.gz
go hpa_omero_xmv.ttl.gz
go hpa_omero_xmw.ttl.gz
go hpa_omero_xmx.ttl.gz
go hpa_omero_xmy.ttl.gz
go hpa_omero_xmz.ttl.gz
go hpa_omero_xna.ttl.gz
go hpa_omero_xnb.ttl.gz
go hpa_omero_xnc.ttl.gz
go hpa_omero_xnd.ttl.gz
go hpa_omero_xne.ttl.gz
go hpa_omero_xnf.ttl.gz
go hpa_omero_xng.ttl.gz
go hpa_omero_xnh.ttl.gz
go hpa_omero_xni.ttl.gz
go hpa_omero_xnj.ttl.gz
go hpa_omero_xnk.ttl.gz
go hpa_omero_xnl.ttl.gz
go hpa_omero_xnm.ttl.gz
go hpa_omero_xnn.ttl.gz
go hpa_omero_xno.ttl.gz
go hpa_omero_xnp.ttl.gz
go hpa_omero_xnq.ttl.gz
go hpa_omero_xnr.ttl.gz
go hpa_omero_xns.ttl.gz
go hpa_omero_xnt.ttl.gz
go hpa_omero_xnu.ttl.gz
go hpa_omero_xnv.ttl.gz
go hpa_omero_xnw.ttl.gz
go hpa_omero_xnx.ttl.gz
go hpa_omero_xny.ttl.gz
go hpa_omero_xnz.ttl.gz
go hpa_omero_xoa.ttl.gz
go hpa_omero_xob.ttl.gz
go hpa_omero_xoc.ttl.gz
go hpa_omero_xod.ttl.gz
go hpa_omero_xoe.ttl.gz
go hpa_omero_xof.ttl.gz
go hpa_omero_xog.ttl.gz
go hpa_omero_xoh.ttl.gz
go hpa_omero_xoi.ttl.gz
go hpa_omero_xoj.ttl.gz
go hpa_omero_xok.ttl.gz
go hpa_omero_xol.ttl.gz
go hpa_omero_xom.ttl.gz
go hpa_omero_xon.ttl.gz
go hpa_omero_xoo.ttl.gz
go hpa_omero_xop.ttl.gz
go hpa_omero_xoq.ttl.gz
go hpa_omero_xor.ttl.gz
go hpa_omero_xos.ttl.gz
go hpa_omero_xot.ttl.gz
go hpa_omero_xou.ttl.gz
go hpa_omero_xov.ttl.gz
go hpa_omero_xow.ttl.gz
go hpa_omero_xox.ttl.gz
go hpa_omero_xoy.ttl.gz
go hpa_omero_xoz.ttl.gz
go hpa_omero_xpa.ttl.gz
go hpa_omero_xpb.ttl.gz
go hpa_omero_xpc.ttl.gz
go hpa_omero_xpd.ttl.gz
go hpa_omero_xpe.ttl.gz
go hpa_omero_xpf.ttl.gz
go hpa_omero_xpg.ttl.gz
go hpa_omero_xph.ttl.gz
go hpa_omero_xpi.ttl.gz
go hpa_omero_xpj.ttl.gz
go hpa_omero_xpk.ttl.gz
go hpa_omero_xpl.ttl.gz
go hpa_omero_xpm.ttl.gz
go hpa_omero_xpn.ttl.gz
go hpa_omero_xpo.ttl.gz
go hpa_omero_xpp.ttl.gz
go hpa_omero_xpq.ttl.gz
go hpa_omero_xpr.ttl.gz
go hpa_omero_xps.ttl.gz
go hpa_omero_xpt.ttl.gz
go hpa_omero_xpu.ttl.gz
go hpa_omero_xpv.ttl.gz
go hpa_omero_xpw.ttl.gz
go hpa_omero_xpx.ttl.gz
go hpa_omero_xpy.ttl.gz
go hpa_omero_xpz.ttl.gz
go hpa_omero_xqa.ttl.gz
go hpa_omero_xqb.ttl.gz
go hpa_omero_xqc.ttl.gz
go hpa_omero_xqd.ttl.gz
go hpa_omero_xqe.ttl.gz
go hpa_omero_xqf.ttl.gz
go hpa_omero_xqg.ttl.gz
go hpa_omero_xqh.ttl.gz
go hpa_omero_xqi.ttl.gz
go hpa_omero_xqj.ttl.gz
go hpa_omero_xqk.ttl.gz
go hpa_omero_xql.ttl.gz
go hpa_omero_xqm.ttl.gz
go hpa_omero_xqn.ttl.gz
go hpa_omero_xqo.ttl.gz
go hpa_omero_xqp.ttl.gz
go hpa_omero_xqq.ttl.gz
go hpa_omero_xqr.ttl.gz
go hpa_omero_xqs.ttl.gz
go hpa_omero_xqt.ttl.gz
go hpa_omero_xqu.ttl.gz
go hpa_omero_xqv.ttl.gz
go hpa_omero_xqw.ttl.gz
go hpa_omero_xqx.ttl.gz
go hpa_omero_xqy.ttl.gz
go hpa_omero_xqz.ttl.gz
go hpa_omero_xra.ttl.gz
go hpa_omero_xrb.ttl.gz
go hpa_omero_xrc.ttl.gz
go hpa_omero_xrd.ttl.gz
go hpa_omero_xre.ttl.gz
go hpa_omero_xrf.ttl.gz
go hpa_omero_xrg.ttl.gz
go hpa_omero_xrh.ttl.gz
go hpa_omero_xri.ttl.gz
go hpa_omero_xrj.ttl.gz
go hpa_omero_xrk.ttl.gz
go hpa_omero_xrl.ttl.gz
go hpa_omero_xrm.ttl.gz
go hpa_omero_xrn.ttl.gz
go hpa_omero_xro.ttl.gz
go hpa_omero_xrp.ttl.gz
go hpa_omero_xrq.ttl.gz
go hpa_omero_xrr.ttl.gz
go hpa_omero_xrs.ttl.gz
go hpa_omero_xrt.ttl.gz
go hpa_omero_xru.ttl.gz
go hpa_omero_xrv.ttl.gz
go hpa_omero_xrw.ttl.gz
go hpa_omero_xrx.ttl.gz
go hpa_omero_xry.ttl.gz
go hpa_omero_xrz.ttl.gz
go hpa_omero_xsa.ttl.gz
go hpa_omero_xsb.ttl.gz
go hpa_omero_xsc.ttl.gz
go hpa_omero_xsd.ttl.gz
go hpa_omero_xse.ttl.gz
go hpa_omero_xsf.ttl.gz
go hpa_omero_xsg.ttl.gz
go hpa_omero_xsh.ttl.gz
go hpa_omero_xsi.ttl.gz
go hpa_omero_xsj.ttl.gz
go hpa_omero_xsk.ttl.gz
go hpa_omero_xsl.ttl.gz
go hpa_omero_xsm.ttl.gz
go hpa_omero_xsn.ttl.gz
go hpa_omero_xso.ttl.gz
go hpa_omero_xsp.ttl.gz
go hpa_omero_xsq.ttl.gz
go hpa_omero_xsr.ttl.gz
go hpa_omero_xss.ttl.gz
go hpa_omero_xst.ttl.gz
go hpa_omero_xsu.ttl.gz
go hpa_omero_xsv.ttl.gz
go hpa_omero_xsw.ttl.gz
go hpa_omero_xsx.ttl.gz
go hpa_omero_xsy.ttl.gz
go hpa_omero_xsz.ttl.gz
go hpa_omero_xta.ttl.gz
go hpa_omero_xtb.ttl.gz
go hpa_omero_xtc.ttl.gz
go hpa_omero_xtd.ttl.gz
go hpa_omero_xte.ttl.gz
go hpa_omero_xtf.ttl.gz
go hpa_omero_xtg.ttl.gz
go hpa_omero_xth.ttl.gz
go hpa_omero_xti.ttl.gz
go hpa_omero_xtj.ttl.gz
go hpa_omero_xtk.ttl.gz
go hpa_omero_xtl.ttl.gz
go hpa_omero_xtm.ttl.gz
go hpa_omero_xtn.ttl.gz
go hpa_omero_xto.ttl.gz
go hpa_omero_xtp.ttl.gz
go hpa_omero_xtq.ttl.gz
go hpa_omero_xtr.ttl.gz
go hpa_omero_xts.ttl.gz
go hpa_omero_xtt.ttl.gz
go hpa_omero_xtu.ttl.gz
go hpa_omero_xtv.ttl.gz
go hpa_omero_xtw.ttl.gz
go hpa_omero_xtx.ttl.gz
go hpa_omero_xty.ttl.gz
go hpa_omero_xtz.ttl.gz
go hpa_omero_xua.ttl.gz
go hpa_omero_xub.ttl.gz
go hpa_omero_xuc.ttl.gz
go hpa_omero_xud.ttl.gz
go hpa_omero_xue.ttl.gz
go hpa_omero_xuf.ttl.gz
go hpa_omero_xug.ttl.gz
go hpa_omero_xuh.ttl.gz
go hpa_omero_xui.ttl.gz
go hpa_omero_xuj.ttl.gz
go hpa_omero_xuk.ttl.gz
go hpa_omero_xul.ttl.gz
go hpa_omero_xum.ttl.gz
go hpa_omero_xun.ttl.gz
go hpa_omero_xuo.ttl.gz
go hpa_omero_xup.ttl.gz
go hpa_omero_xuq.ttl.gz
go hpa_omero_xur.ttl.gz
go hpa_omero_xus.ttl.gz
go hpa_omero_xut.ttl.gz
go hpa_omero_xuu.ttl.gz
go hpa_omero_xuv.ttl.gz
go hpa_omero_xuw.ttl.gz
go hpa_omero_xux.ttl.gz
go hpa_omero_xuy.ttl.gz
go hpa_omero_xuz.ttl.gz
go hpa_omero_xva.ttl.gz
go hpa_omero_xvb.ttl.gz
go hpa_omero_xvc.ttl.gz
go hpa_omero_xvd.ttl.gz
go hpa_omero_xve.ttl.gz
go hpa_omero_xvf.ttl.gz
go hpa_omero_xvg.ttl.gz
go hpa_omero_xvh.ttl.gz
go hpa_omero_xvi.ttl.gz
go hpa_omero_xvj.ttl.gz
go hpa_omero_xvk.ttl.gz
go hpa_omero_xvl.ttl.gz
go hpa_omero_xvm.ttl.gz
go hpa_omero_xvn.ttl.gz
go hpa_omero_xvo.ttl.gz
go hpa_omero_xvp.ttl.gz
go hpa_omero_xvq.ttl.gz
go hpa_omero_xvr.ttl.gz
go hpa_omero_xvs.ttl.gz
go hpa_omero_xvt.ttl.gz
go hpa_omero_xvu.ttl.gz
go hpa_omero_xvv.ttl.gz
go hpa_omero_xvw.ttl.gz
go hpa_omero_xvx.ttl.gz
go hpa_omero_xvy.ttl.gz
go hpa_omero_xvz.ttl.gz
go hpa_omero_xwa.ttl.gz
go hpa_omero_xwb.ttl.gz
go hpa_omero_xwc.ttl.gz
go hpa_omero_xwd.ttl.gz
go hpa_omero_xwe.ttl.gz
go hpa_omero_xwf.ttl.gz
go hpa_omero_xwg.ttl.gz
go hpa_omero_xwh.ttl.gz
go hpa_omero_xwi.ttl.gz
go hpa_omero_xwj.ttl.gz
go hpa_omero_xwk.ttl.gz
go hpa_omero_xwl.ttl.gz
go hpa_omero_xwm.ttl.gz
go hpa_omero_xwn.ttl.gz
go hpa_omero_xwo.ttl.gz
go hpa_omero_xwp.ttl.gz
go hpa_omero_xwq.ttl.gz
go hpa_omero_xwr.ttl.gz
go hpa_omero_xws.ttl.gz
go hpa_omero_xwt.ttl.gz
go hpa_omero_xwu.ttl.gz
go hpa_omero_xwv.ttl.gz
go hpa_omero_xww.ttl.gz
go hpa_omero_xwx.ttl.gz
go hpa_omero_xwy.ttl.gz
go hpa_omero_xwz.ttl.gz
go hpa_omero_xxa.ttl.gz
go hpa_omero_xxb.ttl.gz
go hpa_omero_xxc.ttl.gz
go hpa_omero_xxd.ttl.gz
go hpa_omero_xxe.ttl.gz
go hpa_omero_xxf.ttl.gz
go hpa_omero_xxg.ttl.gz
go hpa_omero_xxh.ttl.gz
go hpa_omero_xxi.ttl.gz
go hpa_omero_xxj.ttl.gz
go hpa_omero_xxk.ttl.gz
go hpa_omero_xxl.ttl.gz
go hpa_omero_xxm.ttl.gz
go hpa_omero_xxn.ttl.gz
go hpa_omero_xxo.ttl.gz
go hpa_omero_xxp.ttl.gz
go hpa_omero_xxq.ttl.gz
go hpa_omero_xxr.ttl.gz
go hpa_omero_xxs.ttl.gz
go hpa_omero_xxt.ttl.gz
go hpa_omero_xxu.ttl.gz
go hpa_omero_xxv.ttl.gz
go hpa_omero_xxw.ttl.gz
go hpa_omero_xxx.ttl.gz
go hpa_omero_xxy.ttl.gz
go hpa_omero_xxz.ttl.gz
go hpa_omero_xya.ttl.gz
go hpa_omero_xyb.ttl.gz
go hpa_omero_xyc.ttl.gz
go hpa_omero_xyd.ttl.gz
go hpa_omero_xye.ttl.gz
go hpa_omero_xyf.ttl.gz
go hpa_omero_xyg.ttl.gz
go hpa_omero_xyh.ttl.gz
go hpa_omero_xyi.ttl.gz
go hpa_omero_xyj.ttl.gz
go hpa_omero_xyk.ttl.gz
go hpa_omero_xyl.ttl.gz
go hpa_omero_xym.ttl.gz
go hpa_omero_xyn.ttl.gz
go hpa_omero_xyo.ttl.gz
go hpa_omero_xyp.ttl.gz
go hpa_omero_xyq.ttl.gz
go hpa_omero_xyr.ttl.gz
go hpa_omero_xys.ttl.gz
go hpa_omero_xyt.ttl.gz
go hpa_omero_xyu.ttl.gz
go hpa_omero_xyv.ttl.gz
go hpa_omero_xyw.ttl.gz
go hpa_omero_xyx.ttl.gz
go hpa_omero_xyy.ttl.gz
go hpa_omero_xyz.ttl.gz
go hpa_omero_xzaaa.ttl.gz
go hpa_omero_xzaab.ttl.gz
go hpa_omero_xzaac.ttl.gz
go hpa_omero_xzaad.ttl.gz
go hpa_omero_xzaae.ttl.gz
go hpa_omero_xzaaf.ttl.gz
go hpa_omero_xzaag.ttl.gz
go hpa_omero_xzaah.ttl.gz
go hpa_omero_xzaai.ttl.gz
go hpa_omero_xzaaj.ttl.gz
go hpa_omero_xzaak.ttl.gz
go hpa_omero_xzaal.ttl.gz
go hpa_omero_xzaam.ttl.gz
go hpa_omero_xzaan.ttl.gz
go hpa_omero_xzaao.ttl.gz
go hpa_omero_xzaap.ttl.gz
go hpa_omero_xzaaq.ttl.gz
go hpa_omero_xzaar.ttl.gz
go hpa_omero_xzaas.ttl.gz
go hpa_omero_xzaat.ttl.gz
go hpa_omero_xzaau.ttl.gz
go hpa_omero_xzaav.ttl.gz
go hpa_omero_xzaaw.ttl.gz
go hpa_omero_xzaax.ttl.gz
go hpa_omero_xzaay.ttl.gz
go hpa_omero_xzaaz.ttl.gz
go hpa_omero_xzaba.ttl.gz
go hpa_omero_xzabb.ttl.gz
go hpa_omero_xzabc.ttl.gz
go hpa_omero_xzabd.ttl.gz
go hpa_omero_xzabe.ttl.gz
go hpa_omero_xzabf.ttl.gz
go hpa_omero_xzabg.ttl.gz
go hpa_omero_xzabh.ttl.gz
go hpa_omero_xzabi.ttl.gz
go hpa_omero_xzabj.ttl.gz
go hpa_omero_xzabk.ttl.gz
go hpa_omero_xzabl.ttl.gz
go hpa_omero_xzabm.ttl.gz
go hpa_omero_xzabn.ttl.gz
go hpa_omero_xzabo.ttl.gz
go hpa_omero_xzabp.ttl.gz
go hpa_omero_xzabq.ttl.gz
go hpa_omero_xzabr.ttl.gz
go hpa_omero_xzabs.ttl.gz
go hpa_omero_xzabt.ttl.gz
go hpa_omero_xzabu.ttl.gz
go hpa_omero_xzabv.ttl.gz
go hpa_omero_xzabw.ttl.gz
go hpa_omero_xzabx.ttl.gz
go hpa_omero_xzaby.ttl.gz
go hpa_omero_xzabz.ttl.gz
go hpa_omero_xzaca.ttl.gz
go hpa_omero_xzacb.ttl.gz
go hpa_omero_xzacc.ttl.gz
go hpa_omero_xzacd.ttl.gz
go hpa_omero_xzace.ttl.gz
go hpa_omero_xzacf.ttl.gz
go hpa_omero_xzacg.ttl.gz
go hpa_omero_xzach.ttl.gz
go hpa_omero_xzaci.ttl.gz
go hpa_omero_xzacj.ttl.gz
go hpa_omero_xzack.ttl.gz
go hpa_omero_xzacl.ttl.gz
go hpa_omero_xzacm.ttl.gz
go hpa_omero_xzacn.ttl.gz
go hpa_omero_xzaco.ttl.gz
go hpa_omero_xzacp.ttl.gz
go hpa_omero_xzacq.ttl.gz
go hpa_omero_xzacr.ttl.gz
go hpa_omero_xzacs.ttl.gz
go hpa_omero_xzact.ttl.gz
go hpa_omero_xzacu.ttl.gz
go hpa_omero_xzacv.ttl.gz
go hpa_omero_xzacw.ttl.gz
go hpa_omero_xzacx.ttl.gz
go hpa_omero_xzacy.ttl.gz
go hpa_omero_xzacz.ttl.gz
go hpa_omero_xzada.ttl.gz
go hpa_omero_xzadb.ttl.gz
go hpa_omero_xzadc.ttl.gz
go hpa_omero_xzadd.ttl.gz
go hpa_omero_xzade.ttl.gz
go hpa_omero_xzadf.ttl.gz
go hpa_omero_xzadg.ttl.gz
go hpa_omero_xzadh.ttl.gz
go hpa_omero_xzadi.ttl.gz
go hpa_omero_xzadj.ttl.gz
go hpa_omero_xzadk.ttl.gz
go hpa_omero_xzadl.ttl.gz
go hpa_omero_xzadm.ttl.gz
go hpa_omero_xzadn.ttl.gz
go hpa_omero_xzado.ttl.gz
go hpa_omero_xzadp.ttl.gz
go hpa_omero_xzadq.ttl.gz
go hpa_omero_xzadr.ttl.gz
go hpa_omero_xzads.ttl.gz
go hpa_omero_xzadt.ttl.gz
go hpa_omero_xzadu.ttl.gz
go hpa_omero_xzadv.ttl.gz
go hpa_omero_xzadw.ttl.gz
go hpa_omero_xzadx.ttl.gz
go hpa_omero_xzady.ttl.gz
go hpa_omero_xzadz.ttl.gz
go hpa_omero_xzaea.ttl.gz
go hpa_omero_xzaeb.ttl.gz
go hpa_omero_xzaec.ttl.gz
go hpa_omero_xzaed.ttl.gz
go hpa_omero_xzaee.ttl.gz
go hpa_omero_xzaef.ttl.gz
go hpa_omero_xzaeg.ttl.gz
go hpa_omero_xzaeh.ttl.gz
go hpa_omero_xzaei.ttl.gz
go hpa_omero_xzaej.ttl.gz
go hpa_omero_xzaek.ttl.gz
go hpa_omero_xzael.ttl.gz
go hpa_omero_xzaem.ttl.gz
go hpa_omero_xzaen.ttl.gz
go hpa_omero_xzaeo.ttl.gz
go hpa_omero_xzaep.ttl.gz
go hpa_omero_xzaeq.ttl.gz
go hpa_omero_xzaer.ttl.gz
go hpa_omero_xzaes.ttl.gz
go hpa_omero_xzaet.ttl.gz
go hpa_omero_xzaeu.ttl.gz
go hpa_omero_xzaev.ttl.gz
go hpa_omero_xzaew.ttl.gz
go hpa_omero_xzaex.ttl.gz
go hpa_omero_xzaey.ttl.gz
go hpa_omero_xzaez.ttl.gz
go hpa_omero_xzafa.ttl.gz
go hpa_omero_xzafb.ttl.gz
go hpa_omero_xzafc.ttl.gz
go hpa_omero_xzafd.ttl.gz
go hpa_omero_xzafe.ttl.gz
go hpa_omero_xzaff.ttl.gz
go hpa_omero_xzafg.ttl.gz
go hpa_omero_xzafh.ttl.gz
go hpa_omero_xzafi.ttl.gz
go hpa_omero_xzafj.ttl.gz
go hpa_omero_xzafk.ttl.gz
go hpa_omero_xzafl.ttl.gz
go hpa_omero_xzafm.ttl.gz
go hpa_omero_xzafn.ttl.gz
go hpa_omero_xzafo.ttl.gz
go hpa_omero_xzafp.ttl.gz
go hpa_omero_xzafq.ttl.gz
go hpa_omero_xzafr.ttl.gz
go hpa_omero_xzafs.ttl.gz
go hpa_omero_xzaft.ttl.gz
go hpa_omero_xzafu.ttl.gz
go hpa_omero_xzafv.ttl.gz
go hpa_omero_xzafw.ttl.gz
go hpa_omero_xzafx.ttl.gz
go hpa_omero_xzafy.ttl.gz
go hpa_omero_xzafz.ttl.gz
go hpa_omero_xzaga.ttl.gz
go hpa_omero_xzagb.ttl.gz
go hpa_omero_xzagc.ttl.gz
go hpa_omero_xzagd.ttl.gz
go hpa_omero_xzage.ttl.gz
go hpa_omero_xzagf.ttl.gz
go hpa_omero_xzagg.ttl.gz
go hpa_omero_xzagh.ttl.gz
go hpa_omero_xzagi.ttl.gz
go hpa_omero_xzagj.ttl.gz
go hpa_omero_xzagk.ttl.gz
go hpa_omero_xzagl.ttl.gz
go hpa_omero_xzagm.ttl.gz
go hpa_omero_xzagn.ttl.gz
go hpa_omero_xzago.ttl.gz
go hpa_omero_xzagp.ttl.gz
go hpa_omero_xzagq.ttl.gz
go hpa_omero_xzagr.ttl.gz
go hpa_omero_xzags.ttl.gz
go hpa_omero_xzagt.ttl.gz
go hpa_omero_xzagu.ttl.gz
go hpa_omero_xzagv.ttl.gz
go hpa_omero_xzagw.ttl.gz
go hpa_omero_xzagx.ttl.gz
go hpa_omero_xzagy.ttl.gz
go hpa_omero_xzagz.ttl.gz
go hpa_omero_xzaha.ttl.gz
go hpa_omero_xzahb.ttl.gz
go hpa_omero_xzahc.ttl.gz
go hpa_omero_xzahd.ttl.gz
go hpa_omero_xzahe.ttl.gz
go hpa_omero_xzahf.ttl.gz
go hpa_omero_xzahg.ttl.gz
go hpa_omero_xzahh.ttl.gz
go hpa_omero_xzahi.ttl.gz
go hpa_omero_xzahj.ttl.gz
go hpa_omero_xzahk.ttl.gz
go hpa_omero_xzahl.ttl.gz
go hpa_omero_xzahm.ttl.gz
go hpa_omero_xzahn.ttl.gz
go hpa_omero_xzaho.ttl.gz
go hpa_omero_xzahp.ttl.gz
go hpa_omero_xzahq.ttl.gz
go hpa_omero_xzahr.ttl.gz
go hpa_omero_xzahs.ttl.gz
go hpa_omero_xzaht.ttl.gz
go hpa_omero_xzahu.ttl.gz
go hpa_omero_xzahv.ttl.gz
go hpa_omero_xzahw.ttl.gz
go hpa_omero_xzahx.ttl.gz
go hpa_omero_xzahy.ttl.gz
go hpa_omero_xzahz.ttl.gz
go hpa_omero_xzaia.ttl.gz
go hpa_omero_xzaib.ttl.gz
go hpa_omero_xzaic.ttl.gz
go hpa_omero_xzaid.ttl.gz
go hpa_omero_xzaie.ttl.gz
go hpa_omero_xzaif.ttl.gz
go hpa_omero_xzaig.ttl.gz
go hpa_omero_xzaih.ttl.gz
go hpa_omero_xzaii.ttl.gz
go hpa_omero_xzaij.ttl.gz
go hpa_omero_xzaik.ttl.gz
go hpa_omero_xzail.ttl.gz
go hpa_omero_xzaim.ttl.gz
go hpa_omero_xzain.ttl.gz
go hpa_omero_xzaio.ttl.gz
go hpa_omero_xzaip.ttl.gz
go hpa_omero_xzaiq.ttl.gz
go hpa_omero_xzair.ttl.gz
go hpa_omero_xzais.ttl.gz
go hpa_omero_xzait.ttl.gz
go hpa_omero_xzaiu.ttl.gz
go hpa_omero_xzaiv.ttl.gz
go hpa_omero_xzaiw.ttl.gz
go hpa_omero_xzaix.ttl.gz
go hpa_omero_xzaiy.ttl.gz
go hpa_omero_xzaiz.ttl.gz
go hpa_omero_xzaja.ttl.gz
go hpa_omero_xzajb.ttl.gz
go hpa_omero_xzajc.ttl.gz
go hpa_omero_xzajd.ttl.gz
go hpa_omero_xzaje.ttl.gz
go hpa_omero_xzajf.ttl.gz
go hpa_omero_xzajg.ttl.gz
go hpa_omero_xzajh.ttl.gz
go hpa_omero_xzaji.ttl.gz
go hpa_omero_xzajj.ttl.gz
go hpa_omero_xzajk.ttl.gz
go hpa_omero_xzajl.ttl.gz
go hpa_omero_xzajm.ttl.gz
go hpa_omero_xzajn.ttl.gz
go hpa_omero_xzajo.ttl.gz
go hpa_omero_xzajp.ttl.gz
go hpa_omero_xzajq.ttl.gz
go hpa_omero_xzajr.ttl.gz
go hpa_omero_xzajs.ttl.gz
go hpa_omero_xzajt.ttl.gz
go hpa_omero_xzaju.ttl.gz
go hpa_omero_xzajv.ttl.gz
go hpa_omero_xzajw.ttl.gz
go hpa_omero_xzajx.ttl.gz
go hpa_omero_xzajy.ttl.gz
go hpa_omero_xzajz.ttl.gz
go hpa_omero_xzaka.ttl.gz
go hpa_omero_xzakb.ttl.gz
go hpa_omero_xzakc.ttl.gz
go hpa_omero_xzakd.ttl.gz
go hpa_omero_xzake.ttl.gz
go hpa_omero_xzakf.ttl.gz
go hpa_omero_xzakg.ttl.gz
go hpa_omero_xzakh.ttl.gz
go hpa_omero_xzaki.ttl.gz
go hpa_omero_xzakj.ttl.gz
go hpa_omero_xzakk.ttl.gz
go hpa_omero_xzakl.ttl.gz
go hpa_omero_xzakm.ttl.gz
go hpa_omero_xzakn.ttl.gz
go hpa_omero_xzako.ttl.gz
go hpa_omero_xzakp.ttl.gz
go hpa_omero_xzakq.ttl.gz
go hpa_omero_xzakr.ttl.gz
go hpa_omero_xzaks.ttl.gz
go hpa_omero_xzakt.ttl.gz
go hpa_omero_xzaku.ttl.gz
go hpa_omero_xzakv.ttl.gz
go hpa_omero_xzakw.ttl.gz
go hpa_omero_xzakx.ttl.gz
go hpa_omero_xzaky.ttl.gz
go hpa_omero_xzakz.ttl.gz
go hpa_omero_xzala.ttl.gz
go hpa_omero_xzalb.ttl.gz
go hpa_omero_xzalc.ttl.gz
go hpa_omero_xzald.ttl.gz
go hpa_omero_xzale.ttl.gz
go hpa_omero_xzalf.ttl.gz
go hpa_omero_xzalg.ttl.gz
go hpa_omero_xzalh.ttl.gz
go hpa_omero_xzali.ttl.gz
go hpa_omero_xzalj.ttl.gz
go hpa_omero_xzalk.ttl.gz
go hpa_omero_xzall.ttl.gz
go hpa_omero_xzalm.ttl.gz
go hpa_omero_xzaln.ttl.gz
go hpa_omero_xzalo.ttl.gz
go hpa_omero_xzalp.ttl.gz
go hpa_omero_xzalq.ttl.gz
go hpa_omero_xzalr.ttl.gz
go hpa_omero_xzals.ttl.gz
go hpa_omero_xzalt.ttl.gz
go hpa_omero_xzalu.ttl.gz
go hpa_omero_xzalv.ttl.gz

$TEXTINDEXER
$TDBSTATS --graph urn:x-arq:UnionGraph > /tmp/stats.opt
mv /tmp/stats.opt $FUSEKI_BASE/databases/tdb/
